-- MySQL Script generated by MySQL Workbench
-- Fri Jul 23 00:44:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
CREATE DATABASE IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roadname_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roadname_code` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roadname_code` (
  `roadname_code` VARCHAR(12) NOT NULL COMMENT '도로명주소 코드. PK1',
  `roadname` VARCHAR(80) NULL COMMENT '도로명',
  `roadname_eng` VARCHAR(80) NULL COMMENT '도로명 로마자',
  `eupmyeondong_number` VARCHAR(2) NOT NULL COMMENT '읍면동일련번호. PK2',
  `sido_name` VARCHAR(20) NULL COMMENT '시도명',
  `sido_eng` VARCHAR(40) NULL COMMENT '시도명 로마자',
  `sigungu` VARCHAR(20) NULL COMMENT '시군구명',
  `sigungu_eng` VARCHAR(40) NULL COMMENT '시군구명 로마자',
  `eupmyeondong` VARCHAR(20) NULL COMMENT '읍면동명',
  `eupmyeondong_eng` VARCHAR(40) NULL COMMENT '읍면동명 로마자',
  `eupmyeondong_type` VARCHAR(1) NULL COMMENT '읍면동구분. 0: 읍면, 1: 동, 2: 미부여',
  `eupmyeondong_code` VARCHAR(3) NULL COMMENT '읍면동코드. 법정동 기준 읍면동 코드',
  `is_using` VARCHAR(1) NULL COMMENT '사용여부. 1일때 사용',
  `change_reason` VARCHAR(1) NULL COMMENT '변경사유. 0: 도로명 변경, 1: 도로명 폐지, 2: 시도시군구변경, 3: 읍면동변경, 4: 영문도로명변경, 9: 기타',
  `change_history` VARCHAR(14) NULL COMMENT '변경이력정보. 도로명코드(12) + 읍면동일련번호(2). 신규일경우 \"신규\"로 표시',
  `declare_date` VARCHAR(8) NULL COMMENT '고시일자',
  `expire_date` VARCHAR(8) NULL COMMENT '말소일자',
  PRIMARY KEY (`roadname_code`, `eupmyeondong_number`),
  UNIQUE INDEX `roadname_code_UNIQUE` (`roadname_code` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '도로명 테이블';


-- -----------------------------------------------------
-- Table `mydb`.`roadname_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roadname_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roadname_address` (
  `manage_number` VARCHAR(25) NOT NULL COMMENT '관리번호. PK.',
  `basement` VARCHAR(1) NULL COMMENT '지하여부. 0: 지상, 1: 지하',
  `building_primary_number` SMALLINT NULL COMMENT '건물본번',
  `building_secondary_number` SMALLINT NULL COMMENT '건물부번',
  `basic_area_number` VARCHAR(5) NULL COMMENT '기초구역번호',
  `change_reason_code` VARCHAR(2) NULL COMMENT '변경사유코드',
  `notice_date` VARCHAR(8) NULL COMMENT '고시일자',
  `previous_roadname_address` VARCHAR(25) NULL COMMENT '변경전도로명주소',
  `has_detail` VARCHAR(1) NULL COMMENT '상세주소부여여부. 0: 미부여, 1: 부여',
  `roadname_code` VARCHAR(12) NOT NULL,
  `eupmyeondong_number` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`manage_number`, `roadname_code`, `eupmyeondong_number`),
  INDEX `fk_address_roadname_idx` (`roadname_code` ASC, `eupmyeondong_number` ASC) VISIBLE,
  CONSTRAINT `fk_address_roadname`
    FOREIGN KEY (`roadname_code` , `eupmyeondong_number`)
    REFERENCES `mydb`.`roadname_code` (`roadname_code` , `eupmyeondong_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '도로명주소 테이블';


-- -----------------------------------------------------
-- Table `mydb`.`jibun_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jibun_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jibun_address` (
  `serial_number` SMALLINT NOT NULL COMMENT '일련번호. PK2.',
  `bupjungdong_code` VARCHAR(10) CHARACTER SET 'utf8mb4' NOT NULL COMMENT '법정동코드',
  `sido_name` VARCHAR(20) NOT NULL COMMENT '시도명',
  `sigungu_name` VARCHAR(20) NOT NULL COMMENT '시군구명',
  `bupjung_eupmyeondong_name` VARCHAR(20) NOT NULL COMMENT '법정읍면동명',
  `bupjunglee_name` VARCHAR(20) NOT NULL COMMENT '법정리명',
  `is_mountain` VARCHAR(1) NOT NULL COMMENT '산 여부. 1일 때 산',
  `jibun_primary` SMALLINT NOT NULL COMMENT '지번본번(번지)',
  `jibun_secondary` SMALLINT NOT NULL COMMENT '지번부번(호)',
  `is_representation` VARCHAR(1) NOT NULL COMMENT '대표여부. 0: 관련지번, 1: 대표지번',
  `manage_number` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`serial_number`, `manage_number`),
  INDEX `fk_jibun_address1_idx` (`manage_number` ASC) VISIBLE,
  UNIQUE INDEX `manage_number_UNIQUE` (`manage_number` ASC) VISIBLE,
  CONSTRAINT `fk_jibun_address1`
    FOREIGN KEY (`manage_number`)
    REFERENCES `mydb`.`roadname_address` (`manage_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '지번주소 테이블';


-- -----------------------------------------------------
-- Table `mydb`.`additional_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`additional_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`additional_info` (
  `manage_number` VARCHAR(25) NOT NULL COMMENT '관리번호',
  `hangjungdong_code` VARCHAR(10) NULL COMMENT '행정동코드',
  `hangjungdong_name` VARCHAR(20) NULL COMMENT '행정동명',
  `zipcode` VARCHAR(5) NULL COMMENT '우편번호',
  `zipcode_serial_number` VARCHAR(3) NULL COMMENT '우편번호 일련번호',
  `bulk_delivery_building_name` VARCHAR(40) NULL COMMENT '다량배달처명',
  `master_building_name` VARCHAR(40) NULL COMMENT '건축물대장 건물명',
  `sigungu_building_name` VARCHAR(40) NULL COMMENT '시군구 건물명',
  `is_apt` VARCHAR(1) NULL COMMENT '공동주택여부',
  PRIMARY KEY (`manage_number`),
  UNIQUE INDEX `manage_number_UNIQUE` (`manage_number` ASC) VISIBLE,
  CONSTRAINT `fk_additional_info_roadname_address1`
    FOREIGN KEY (`manage_number`)
    REFERENCES `mydb`.`roadname_address` (`manage_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
